name: Deploy

# Trigger the workflow on push and
# pull request events on the master branch
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x] # Update to match your project's Node.js version

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: 'cd /var/www/github-actions-vps && ./.scripts/deploy.sh'
