name: Deploy Next App
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          SSHKEY: ${{ secrets.SSHKEY }}
      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy and Reload with pm2
        run: pm2 reload github-actions-vps
